// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7hf2obiEQrL9N--kqMk270a5zcL_Vz_o',
    appId: '1:100158083172:web:ff397caf90a28580b74f71',
    messagingSenderId: '100158083172',
    projectId: 'laptopharbour-15ceb',
    authDomain: 'laptopharbour-15ceb.firebaseapp.com',
    storageBucket: 'laptopharbour-15ceb.appspot.com',
    measurementId: 'G-315KL5Q8TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsEDdChA_MORzOY5Akw6ZEE9rhTRz9izM',
    appId: '1:100158083172:android:cd21c70e8ca4580fb74f71',
    messagingSenderId: '100158083172',
    projectId: 'laptopharbour-15ceb',
    storageBucket: 'laptopharbour-15ceb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6BU1WWTxRROJ3UhQ8wjWWmAzm-ht3sF8',
    appId: '1:100158083172:ios:1544be262c1b7693b74f71',
    messagingSenderId: '100158083172',
    projectId: 'laptopharbour-15ceb',
    storageBucket: 'laptopharbour-15ceb.appspot.com',
    iosClientId: '100158083172-lh42q9kn8kj34rcsf31j5g9l52sathci.apps.googleusercontent.com',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6BU1WWTxRROJ3UhQ8wjWWmAzm-ht3sF8',
    appId: '1:100158083172:ios:1544be262c1b7693b74f71',
    messagingSenderId: '100158083172',
    projectId: 'laptopharbour-15ceb',
    storageBucket: 'laptopharbour-15ceb.appspot.com',
    iosClientId: '100158083172-lh42q9kn8kj34rcsf31j5g9l52sathci.apps.googleusercontent.com',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7hf2obiEQrL9N--kqMk270a5zcL_Vz_o',
    appId: '1:100158083172:web:e33e6d13b6d8ecc8b74f71',
    messagingSenderId: '100158083172',
    projectId: 'laptopharbour-15ceb',
    authDomain: 'laptopharbour-15ceb.firebaseapp.com',
    storageBucket: 'laptopharbour-15ceb.appspot.com',
    measurementId: 'G-RCJLTTTF34',
  );
}
